import 'dotenv/config';
import express from 'express';
import http from 'node:http';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import mongoose, {Schema, model} from 'mongoose';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import multer from 'multer';
import rateLimit from 'express-rate-limit';
import {Server as SocketServer} from 'socket.io';
import {createAdapter} from '@socket.io/redis-adapter';
import Redis from 'ioredis';
import {v2 as cloudinary} from 'cloudinary';
import {z} from 'zod';

const env = {port:Number(process.env.PORT ?? 4000), mongo:process.env.MONGO_URI ?? 'mongodb://localhost:27017/relay', jwt:process.env.JWT_SECRET ?? 'dev-secret-change-me', refresh:process.env.JWT_REFRESH_SECRET ?? 'dev-refresh-change-me'};
const id = () => crypto.randomUUID();

const User = model('User', new Schema({displayName:{type:String,required:true,trim:true},email:{type:String,required:true,unique:true,lowercase:true,trim:true},passwordHash:{type:String,required:true},avatarUrl:String,createdAt:{type:Date,default:Date.now}}));
const RefreshSession = model('RefreshSession', new Schema({userId:{type:Schema.Types.ObjectId,ref:'User',index:true},tokenHash:String,expiresAt:Date,revokedAt:Date,createdAt:{type:Date,default:Date.now}}));
const Workspace = model('Workspace', new Schema({name:{type:String,required:true,trim:true},ownerId:{type:Schema.Types.ObjectId,ref:'User',required:true,index:true},joinCodeHash:{type:String,required:true},joinCode:String,joinCodeLast4:String,createdAt:{type:Date,default:Date.now}}));
const WorkspaceMember = model('WorkspaceMember', new Schema({workspaceId:{type:Schema.Types.ObjectId,ref:'Workspace',index:true},userId:{type:Schema.Types.ObjectId,ref:'User',index:true},role:{type:String,enum:['owner','admin','member'],default:'member'},joinedAt:{type:Date,default:Date.now}}));
WorkspaceMember.schema.index({workspaceId:1,userId:1},{unique:true});
const Channel = model('Channel', new Schema({workspaceId:{type:Schema.Types.ObjectId,ref:'Workspace',index:true},name:{type:String,required:true,lowercase:true,trim:true},description:String,visibility:{type:String,enum:['public','private'],default:'public'},archivedAt:Date,createdBy:{type:Schema.Types.ObjectId,ref:'User'},createdAt:{type:Date,default:Date.now}}));
const ChannelMember = model('ChannelMember', new Schema({channelId:{type:Schema.Types.ObjectId,ref:'Channel',index:true},userId:{type:Schema.Types.ObjectId,ref:'User',index:true},joinedAt:{type:Date,default:Date.now}}));
ChannelMember.schema.index({channelId:1,userId:1},{unique:true});
const Conversation = model('Conversation', new Schema({kind:{type:String,enum:['direct','channel'],required:true},workspaceId:{type:Schema.Types.ObjectId,ref:'Workspace',index:true},channelId:{type:Schema.Types.ObjectId,ref:'Channel',index:true},participantIds:[{type:Schema.Types.ObjectId,ref:'User',index:true}],participantKey:{type:String},createdAt:{type:Date,default:Date.now}}));
Conversation.schema.index({kind:1,workspaceId:1,participantKey:1},{unique:true,sparse:true});
const Message = model('Message', new Schema({conversationId:{type:Schema.Types.ObjectId,ref:'Conversation',index:true},senderId:{type:Schema.Types.ObjectId,ref:'User',index:true},clientId:String,text:{type:String,default:''},attachments:[{url:String,name:String,mimeType:String,size:Number,publicId:String}],replyTo:{type:Schema.Types.ObjectId,ref:'Message'},editedAt:Date,deletedAt:Date,createdAt:{type:Date,default:Date.now}}));
Message.schema.index({conversationId:1,createdAt:-1});
const ReadState = model('ReadState', new Schema({conversationId:{type:Schema.Types.ObjectId,ref:'Conversation',index:true},userId:{type:Schema.Types.ObjectId,ref:'User',index:true},lastReadMessageId:Schema.Types.ObjectId,readAt:Date}));
ReadState.schema.index({conversationId:1,userId:1},{unique:true});

type AuthedRequest = express.Request & {user?:any};
const access = (user:any) => jwt.sign({sub:user._id.toString(),email:user.email,displayName:user.displayName},env.jwt,{expiresIn:'15m'});
const refresh = (user:any) => jwt.sign({sub:user._id.toString(),jti:id()},env.refresh,{expiresIn:'30d'});
const hashToken = (token:string) => crypto.createHash('sha256').update(token).digest('hex');
const auth = (req:AuthedRequest,res:express.Response,next:express.NextFunction) => {try{const header=req.headers.authorization; if(!header?.startsWith('Bearer ')) throw new Error('missing'); req.user=jwt.verify(header.slice(7),env.jwt); next();}catch{res.status(401).json({error:'Unauthorized'});}};
const asyncRoute = (fn:any) => (req:any,res:any,next:any) => Promise.resolve(fn(req,res,next)).catch(next);
const body = (schema:any) => (req:any,res:any,next:any) => {const parsed=schema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Invalid request',details:parsed.error.flatten()});req.body=parsed.data;next();};
const member = async (userId:string, workspaceId:string) => WorkspaceMember.findOne({userId,workspaceId});
const canManage = (m:any) => m && ['owner','admin'].includes(m.role);
const codePair = () => {const raw=crypto.randomBytes(4).toString('hex').toUpperCase();return {raw,hash:hashToken(raw)};};
const publicUser = (u:any) => ({_id:u._id,displayName:u.displayName,email:u.email,avatarUrl:u.avatarUrl});
const configuredOrigins=(process.env.CLIENT_ORIGIN??'').split(',').map(origin=>origin.trim()).filter(Boolean);
const corsOrigin=(origin:string|undefined,callback:(error:Error|null,allow?:boolean)=>void)=>{
  const isLocalDevelopmentOrigin=origin!=null&&/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin);
  if(!origin||configuredOrigins.includes(origin)||isLocalDevelopmentOrigin)return callback(null,true);
  callback(new Error('Origin not allowed by CORS'));
};

const app=express(); app.disable('etag'); app.use(helmet()); app.use(cors({origin:corsOrigin,credentials:true})); app.use(express.json({limit:'1mb'})); app.use(morgan('dev')); app.use(rateLimit({windowMs:60_000,max:120,standardHeaders:true,legacyHeaders:false}));app.use('/api/v1',(_req,_res,next)=>{_res.set('Cache-Control','no-store');next();});
const router=express.Router();
router.get('/health',(_req,res)=>res.status(200).json({status:'ok'}));
router.post('/auth/register',body(z.object({displayName:z.string().min(2).max(60),email:z.email(),password:z.string().min(8).max(128)})),asyncRoute(async(req:any,res:any)=>{const exists=await User.findOne({email:req.body.email});if(exists)return res.status(409).json({error:'Email already registered'});const user=await User.create({displayName:req.body.displayName,email:req.body.email,passwordHash:await bcrypt.hash(req.body.password,12)});const rt=refresh(user);await RefreshSession.create({userId:user._id,tokenHash:hashToken(rt),expiresAt:new Date(Date.now()+30*864e5)});res.status(201).json({user:publicUser(user),accessToken:access(user),refreshToken:rt});}));
router.post('/auth/login',body(z.object({email:z.email(),password:z.string()})),asyncRoute(async(req:any,res:any)=>{const user=await User.findOne({email:req.body.email});if(!user || !(await bcrypt.compare(req.body.password,user.passwordHash)))return res.status(401).json({error:'Invalid email or password'});const rt=refresh(user);await RefreshSession.create({userId:user._id,tokenHash:hashToken(rt),expiresAt:new Date(Date.now()+30*864e5)});res.json({user:publicUser(user),accessToken:access(user),refreshToken:rt});}));
router.post('/auth/refresh',asyncRoute(async(req:any,res:any)=>{const token=req.body?.refreshToken;if(!token)return res.status(401).json({error:'Refresh token required'});try{const p:any=jwt.verify(token,env.refresh);const session=await RefreshSession.findOne({userId:p.sub,tokenHash:hashToken(token),revokedAt:null,expiresAt:{$gt:new Date()}});if(!session)throw new Error('revoked');session.revokedAt=new Date();await session.save();const user=await User.findById(p.sub);if(!user)throw new Error('missing');const next=refresh(user);await RefreshSession.create({userId:user._id,tokenHash:hashToken(next),expiresAt:new Date(Date.now()+30*864e5)});res.json({accessToken:access(user),refreshToken:next});}catch{res.status(401).json({error:'Invalid refresh token'});}}));
router.post('/auth/logout',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{if(req.body?.refreshToken)await RefreshSession.updateOne({userId:req.user.sub,tokenHash:hashToken(req.body.refreshToken)},{revokedAt:new Date()});res.status(204).end();}));
router.get('/auth/me',auth,asyncRoute(async(req:AuthedRequest,res:any)=>res.json({user:publicUser(await User.findById(req.user.sub))})));

router.get('/workspaces',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{const memberships=await WorkspaceMember.find({userId:req.user.sub}).populate('workspaceId');res.json({workspaces:memberships.map((m:any)=>({...m.workspaceId.toObject(),role:m.role,joinCodeLast4:m.workspaceId.joinCodeLast4}))});}));
router.post('/workspaces',auth,body(z.object({name:z.string().min(2).max(80)})),asyncRoute(async(req:AuthedRequest,res:any)=>{const pair=codePair();const w=await Workspace.create({name:req.body.name,ownerId:req.user.sub,joinCodeHash:pair.hash,joinCode:pair.raw,joinCodeLast4:pair.raw.slice(-4)});await WorkspaceMember.create({workspaceId:w._id,userId:req.user.sub,role:'owner'});const channel=await Channel.create({workspaceId:w._id,name:'general',description:'A place for everyone',createdBy:req.user.sub});await ChannelMember.create({channelId:channel._id,userId:req.user.sub});res.status(201).json({workspace:w,joinCode:pair.raw,channel});}));
router.post('/workspaces/join',auth,body(z.object({code:z.string().min(6).max(16)})),asyncRoute(async(req:AuthedRequest,res:any)=>{const w=await Workspace.findOne({joinCodeHash:hashToken(req.body.code.toUpperCase())});if(!w)return res.status(404).json({error:'Invalid join code'});await WorkspaceMember.updateOne({workspaceId:w._id,userId:req.user.sub},{$setOnInsert:{role:'member'}},{upsert:true});res.json({workspace:w});}));
router.post('/workspaces/:id/rotate-code',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{const workspaceId=String(req.params.id);const m=await member(req.user.sub,workspaceId);if(!canManage(m))return res.status(403).json({error:'Admin role required'});const pair=codePair();const w=await Workspace.findByIdAndUpdate(workspaceId,{joinCodeHash:pair.hash,joinCode:pair.raw,joinCodeLast4:pair.raw.slice(-4)},{new:true});res.json({workspace:w,joinCode:pair.raw});}));
router.get('/workspaces/:id/members',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{const workspaceId=String(req.params.id);if(!await member(req.user.sub,workspaceId))return res.status(403).json({error:'Workspace membership required'});const rows=await WorkspaceMember.find({workspaceId}).populate('userId','displayName email avatarUrl');res.json({members:rows});}));
router.patch('/workspaces/:id/members/:userId',auth,body(z.object({role:z.enum(['admin','member'])})),asyncRoute(async(req:AuthedRequest,res:any)=>{const workspaceId=String(req.params.id),userId=String(req.params.userId);const m=await member(req.user.sub,workspaceId);if(!canManage(m))return res.status(403).json({error:'Admin role required'});const row=await WorkspaceMember.findOneAndUpdate({workspaceId,userId},{role:req.body.role},{new:true});res.json({member:row});}));

router.get('/workspaces/:id/channels',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{const workspaceId=String(req.params.id);if(!await member(req.user.sub,workspaceId))return res.status(403).json({error:'Workspace membership required'});const rows=await Channel.find({workspaceId,archivedAt:null});const privateIds=(await ChannelMember.find({userId:req.user.sub,channelId:{$in:rows.filter(x=>x.visibility==='private').map(x=>x._id)}})).map((x:any)=>x.channelId.toString());res.json({channels:rows.filter(x=>x.visibility==='public'||privateIds.includes(x._id.toString()))});}));
router.post('/workspaces/:id/channels',auth,body(z.object({name:z.string().min(1).max(50),description:z.string().max(200).optional(),visibility:z.enum(['public','private']).default('public')})),asyncRoute(async(req:AuthedRequest,res:any)=>{const workspaceId=String(req.params.id);const m=await member(req.user.sub,workspaceId);if(!canManage(m))return res.status(403).json({error:'Admin role required'});const channel=await Channel.create({workspaceId,...req.body,createdBy:req.user.sub});if(req.body.visibility==='private')await ChannelMember.create({channelId:channel._id,userId:req.user.sub});res.status(201).json({channel});}));
router.post('/channels/:id/join',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{const ch:any=await Channel.findById(String(req.params.id));if(!ch||ch.visibility!=='public'||!await member(req.user.sub,String(ch.workspaceId)))return res.status(403).json({error:'Cannot join channel'});await ChannelMember.updateOne({channelId:ch._id,userId:req.user.sub},{$setOnInsert:{joinedAt:new Date()}},{upsert:true});res.json({channel:ch});}));
router.post('/channels/:id/leave',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{const ch:any=await Channel.findById(String(req.params.id));if(!ch)return res.status(404).json({error:'Channel not found'});await ChannelMember.deleteOne({channelId:ch._id,userId:req.user.sub});res.status(204).end();}));
router.patch('/channels/:id',auth,body(z.object({name:z.string().min(1).max(50).optional(),description:z.string().max(200).optional(),visibility:z.enum(['public','private']).optional()})),asyncRoute(async(req:AuthedRequest,res:any)=>{const ch:any=await Channel.findById(String(req.params.id));if(!ch)return res.status(404).json({error:'Channel not found'});const m=await member(req.user.sub,String(ch.workspaceId));if(!canManage(m))return res.status(403).json({error:'Admin role required'});Object.assign(ch,req.body);await ch.save();res.json({channel:ch});}));
router.delete('/channels/:id',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{const ch:any=await Channel.findById(String(req.params.id));if(!ch)return res.status(404).json({error:'Channel not found'});const m=await member(req.user.sub,String(ch.workspaceId));if(!canManage(m))return res.status(403).json({error:'Admin role required'});ch.archivedAt=new Date();await ch.save();res.status(204).end();}));
router.post('/channels/:id/members',auth,body(z.object({userId:z.string()})),asyncRoute(async(req:AuthedRequest,res:any)=>{const ch:any=await Channel.findById(String(req.params.id));if(!ch)return res.status(404).json({error:'Channel not found'});const m=await member(req.user.sub,String(ch.workspaceId));if(!canManage(m)||!await member(req.body.userId,String(ch.workspaceId)))return res.status(403).json({error:'Admin role and workspace membership required'});await ChannelMember.updateOne({channelId:ch._id,userId:req.body.userId},{$setOnInsert:{joinedAt:new Date()}},{upsert:true});res.status(201).json({ok:true});}));
router.delete('/channels/:id/members/:userId',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{const ch:any=await Channel.findById(String(req.params.id));if(!ch)return res.status(404).json({error:'Channel not found'});const m=await member(req.user.sub,String(ch.workspaceId));if(!canManage(m))return res.status(403).json({error:'Admin role required'});await ChannelMember.deleteOne({channelId:ch._id,userId:String(req.params.userId)});res.status(204).end();}));

const authorizedConversation=async(userId:string,conversationId:string)=>{const c:any=await Conversation.findById(conversationId);if(!c)return null;if(c.kind==='direct')return c.participantIds.some((x:any)=>x.toString()===userId)?c:null;const m=await member(userId,c.workspaceId.toString());if(!m)return null;if(c.channelId){const ch:any=await Channel.findById(c.channelId);if(ch?.visibility==='private'&&!await ChannelMember.exists({channelId:ch._id,userId}))return null;}return c;};
router.get('/conversations/:conversationId/details',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{
  const conversation:any=await authorizedConversation(req.user.sub,String(req.params.conversationId));
  if(!conversation)return res.status(403).json({error:'Conversation access denied'});
  if(conversation.kind==='direct'){
    const users=await User.find({_id:{$in:conversation.participantIds}}).select('displayName email avatarUrl');
    return res.json({kind:'direct',members:users.map(publicUser)});
  }
  const channel:any=await Channel.findById(conversation.channelId);
  const workspace:any=await Workspace.findById(conversation.workspaceId);
  if(!channel||!workspace)return res.status(404).json({error:'Conversation details not found'});
  if(!workspace.joinCode){
    const pair=codePair();
    workspace.joinCode=pair.raw;
    workspace.joinCodeHash=pair.hash;
    workspace.joinCodeLast4=pair.raw.slice(-4);
    await workspace.save();
  }
  let membershipQuery:any={workspaceId:workspace._id};
  if(channel.visibility==='private'){
    const channelMembers=await ChannelMember.find({channelId:channel._id});
    membershipQuery={workspaceId:workspace._id,userId:{$in:channelMembers.map((item:any)=>item.userId)}};
  }
  const memberships=await WorkspaceMember.find(membershipQuery).populate('userId','displayName email avatarUrl');
  const members=memberships.map((item:any)=>({...publicUser(item.userId),role:item.role}));
  res.json({kind:'channel',workspace:{_id:workspace._id,name:workspace.name,joinCode:workspace.joinCode},channel:{_id:channel._id,name:channel.name,visibility:channel.visibility},members});
}));
router.get('/conversations',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{const workspaces=await WorkspaceMember.find({userId:req.user.sub});const workspaceDocs=await Workspace.find({_id:{$in:workspaces.map(x=>x.workspaceId)}}).select('name');const workspaceNames=new Map(workspaceDocs.map((w:any)=>[w._id.toString(),w.name]));const allChannels=await Channel.find({workspaceId:{$in:workspaces.map(x=>x.workspaceId)},archivedAt:null});const privateChannels=allChannels.filter((c:any)=>c.visibility==='private');const privateMemberships=await ChannelMember.find({userId:req.user.sub,channelId:{$in:privateChannels.map((c:any)=>c._id)}});const allowedPrivate=new Set(privateMemberships.map((m:any)=>m.channelId.toString()));const channels=allChannels.filter((c:any)=>c.visibility==='public'||allowedPrivate.has(c._id.toString()));const direct=await Conversation.find({kind:'direct',participantIds:req.user.sub}).populate('participantIds','displayName email');const channelConvs=await Promise.all(channels.map(async(ch:any)=>{let c:any=await Conversation.findOne({kind:'channel',channelId:ch._id});if(!c)c=await Conversation.create({kind:'channel',workspaceId:ch.workspaceId,channelId:ch._id});const workspaceName=workspaceNames.get(ch.workspaceId.toString())??'Workspace';return {id:c._id.toString(),title:ch.name==='general'?workspaceName:`# ${ch.name}`,kind:'channel',workspaceId:ch.workspaceId,workspaceName,channelName:ch.name};}));res.json({conversations:[...direct.map((c:any)=>({id:c._id,title:c.participantIds.find((p:any)=>p._id.toString()!==req.user.sub)?.displayName??'Direct chat',kind:'direct',workspaceId:c.workspaceId,workspaceName:workspaceNames.get(c.workspaceId.toString())??'Workspace',online:false})),...channelConvs]});}));
router.post('/conversations/direct',auth,body(z.object({userId:z.string(),workspaceId:z.string()})),asyncRoute(async(req:AuthedRequest,res:any)=>{if(!await member(req.user.sub,req.body.workspaceId)||!await member(req.body.userId,req.body.workspaceId))return res.status(403).json({error:'Both users must be workspace members'});const ids=[req.user.sub,req.body.userId].sort();const participantKey=ids.join(':');const c=await Conversation.findOneAndUpdate({kind:'direct',workspaceId:req.body.workspaceId,participantKey},{$setOnInsert:{kind:'direct',workspaceId:req.body.workspaceId,participantIds:ids,participantKey}},{upsert:true,new:true});res.status(201).json({conversation:c});}));
router.get('/conversations/:conversationId/messages',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{const c=await authorizedConversation(req.user.sub,String(req.params.conversationId));if(!c)return res.status(403).json({error:'Conversation access denied'});const limit=Math.min(Number(req.query.limit??40),100);const query:any={conversationId:c._id};if(req.query.before)query.createdAt={$lt:new Date(String(req.query.before))};const messages=await Message.find(query).sort({createdAt:-1}).limit(limit).populate('senderId','displayName email');res.json({messages:messages.reverse(),nextCursor:messages.length===limit?messages[0].createdAt.toISOString():null});}));
router.patch('/messages/:id',auth,body(z.object({text:z.string().min(1).max(5000)})),asyncRoute(async(req:AuthedRequest,res:any)=>{const msg:any=await Message.findById(req.params.id);if(!msg||msg.senderId.toString()!==req.user.sub||msg.deletedAt)return res.status(404).json({error:'Message not found'});msg.text=req.body.text;msg.editedAt=new Date();await msg.save();io.to(`conversation:${msg.conversationId}`).emit('message:updated',msg);res.json({message:msg});}));
router.delete('/messages/:id',auth,asyncRoute(async(req:AuthedRequest,res:any)=>{const msg:any=await Message.findById(req.params.id);if(!msg||msg.senderId.toString()!==req.user.sub)return res.status(404).json({error:'Message not found'});msg.deletedAt=new Date();msg.text='';await msg.save();io.to(`conversation:${msg.conversationId}`).emit('message:deleted',{id:msg._id,deletedAt:msg.deletedAt});res.status(204).end();}));

const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(_,file,cb)=>cb(null,/^(image\/|application\/pdf|application\/msword|application\/vnd\.|text\/plain)/.test(file.mimetype))});
cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET});
router.post('/uploads',auth,upload.single('file'),asyncRoute(async(req:AuthedRequest,res:any)=>{if(!req.file)return res.status(400).json({error:'Unsupported or missing file'});if(!process.env.CLOUDINARY_CLOUD_NAME)return res.status(503).json({error:'Cloudinary is not configured'});const result:any=await new Promise((resolve,reject)=>{const stream=cloudinary.uploader.upload_stream({resource_type:'auto',folder:'relay-chat'},(err,r)=>err?reject(err):resolve(r));stream.end(req.file!.buffer);});res.status(201).json({attachment:{url:result.secure_url,name:req.file.originalname,mimeType:req.file.mimetype,size:req.file.size,publicId:result.public_id}});}));
app.use('/api/v1',router); app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);res.status(500).json({error:'Internal server error'});});

const httpServer=http.createServer(app); export const io=new SocketServer(httpServer,{cors:{origin:corsOrigin,credentials:true}});
if(process.env.REDIS_URL){const pub=new Redis(process.env.REDIS_URL),sub=pub.duplicate();io.adapter(createAdapter(pub,sub));}
io.use(async(socket,next)=>{try{const token=(socket.handshake.auth as any)?.token;socket.data.user=jwt.verify(token,env.jwt);if(!socket.data.user.displayName){const user:any=await User.findById(socket.data.user.sub).select('displayName');socket.data.user.displayName=user?.displayName;}next();}catch{next(new Error('Unauthorized'));}});
io.on('connection',socket=>{const userId=socket.data.user.sub;const displayName=socket.data.user.displayName??'Someone';socket.join(`user:${userId}`);socket.broadcast.emit('presence:update',{userId,displayName,online:true});socket.on('conversation:join',async({conversationId})=>{if(await authorizedConversation(userId,conversationId))socket.join(`conversation:${conversationId}`);});socket.on('conversation:leave',({conversationId})=>socket.leave(`conversation:${conversationId}`));socket.on('typing:start',async({conversationId})=>{if(!await authorizedConversation(userId,conversationId))return;socket.to(`conversation:${conversationId}`).emit('typing:update',{userId,displayName,typing:true});});socket.on('typing:stop',async({conversationId})=>{if(!await authorizedConversation(userId,conversationId))return;socket.to(`conversation:${conversationId}`).emit('typing:update',{userId,displayName,typing:false});});socket.on('receipt:read',async({conversationId,messageId})=>{if(!await authorizedConversation(userId,conversationId))return;await ReadState.findOneAndUpdate({conversationId,userId},{lastReadMessageId:messageId,readAt:new Date()},{upsert:true});socket.to(`conversation:${conversationId}`).emit('receipt:update',{userId,messageId});});socket.on('message:send',async(payload,ack)=>{try{const c=await authorizedConversation(userId,payload.conversationId);if(!c)throw new Error('Conversation access denied');let msg:any=await Message.findOne({conversationId:c._id,senderId:userId,clientId:payload.clientId});if(!msg){msg=await Message.create({conversationId:c._id,senderId:userId,clientId:payload.clientId,text:String(payload.text??'').slice(0,5000),replyTo:payload.replyTo||undefined,attachments:payload.attachments??[]});msg=await msg.populate('senderId','displayName email');}io.to(`conversation:${c._id}`).emit('message:new',msg);ack?.({ok:true,message:msg,clientId:payload.clientId});}catch(e:any){ack?.({ok:false,error:e.message});socket.emit('operation:error',{operation:'message:send',error:e.message});}});socket.on('disconnect',()=>socket.broadcast.emit('presence:update',{userId,displayName,online:false}));});

if(process.env.NODE_ENV!=='test'){mongoose.connect(env.mongo).then(async()=>{httpServer.listen(env.port,'0.0.0.0',()=>console.log(`SyncUp API listening on ${env.port}`));}).catch(err=>{console.error('Mongo connection failed',err);process.exit(1);});}
export {app,httpServer};
